### ISSUE TITLE
Containerization

### ISSUE THREAD

**Issue by ashleybot** [UK-SBCoA/uniform-data-set-dotnet#16]
- [x] Determine configuration of containers to publish
- [x] Follow repository naming conventions
- [x] Automated pipeline for container publishing

```[tasklist]
### Before end of June
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet/issues/21
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet/issues/22
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet/issues/23
- [ ] https://github.com/UK-SBCoA/uniform-data-set-dotnet/issues/24
```
